[workspace]
members = [
    "crates/zolana-mobile",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/helius-labs/zolana"

[workspace.dependencies]
serde_json = "1.0"

[workspace.metadata.upstream]
repository = "https://github.com/helius-labs/zolana"
revision = "e6139f658c6961101d716e107a15a5ca9cecd143"
