[workspace]
members = [
    "packages/zolana_mobile/native/zolana-mobile",
]
exclude = ["packages/zolana_mobile/native/rust-gnark"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/helius-labs/zolana-mobile-sdk"

[workspace.dependencies]
serde_json = "1.0"

[workspace.metadata.upstream]
repository = "https://github.com/helius-labs/zolana"
revision = "4745bbb3bc60edd08ca0f348ea6cfc6a4ab168f8"
