// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'third_party/zolana_mobile.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1586915465;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mopro_flutter_bindings',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ProvingKeyInfo> zolanaMobileInspectProvingKey({required String path});

  Future<Uint8List> zolanaMobilePoseidonHash({required List<Uint8List> inputs});

  Future<TransferDraft> zolanaMobilePrepareTransfer({
    required TransferDraftRequest request,
  });

  Future<LocalProofResult> zolanaMobileProveAssignment({
    required String provingKeyPath,
    required String assignmentPath,
  });

  Future<String> zolanaMobileSdkVersion();

  Future<String> zolanaMobileShieldedAddress({required List<int> seed});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ProvingKeyInfo> zolanaMobileInspectProvingKey({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_proving_key_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kZolanaMobileInspectProvingKeyConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kZolanaMobileInspectProvingKeyConstMeta =>
      const TaskConstMeta(debugName: "inspect_proving_key", argNames: ["path"]);

  @override
  Future<Uint8List> zolanaMobilePoseidonHash({
    required List<Uint8List> inputs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_list_prim_u_8_strict(inputs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kZolanaMobilePoseidonHashConstMeta,
        argValues: [inputs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kZolanaMobilePoseidonHashConstMeta =>
      const TaskConstMeta(debugName: "poseidon_hash", argNames: ["inputs"]);

  @override
  Future<TransferDraft> zolanaMobilePrepareTransfer({
    required TransferDraftRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_transfer_draft_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_transfer_draft,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kZolanaMobilePrepareTransferConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kZolanaMobilePrepareTransferConstMeta =>
      const TaskConstMeta(debugName: "prepare_transfer", argNames: ["request"]);

  @override
  Future<LocalProofResult> zolanaMobileProveAssignment({
    required String provingKeyPath,
    required String assignmentPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(provingKeyPath, serializer);
          sse_encode_String(assignmentPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_local_proof_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kZolanaMobileProveAssignmentConstMeta,
        argValues: [provingKeyPath, assignmentPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kZolanaMobileProveAssignmentConstMeta =>
      const TaskConstMeta(
        debugName: "prove_assignment",
        argNames: ["provingKeyPath", "assignmentPath"],
      );

  @override
  Future<String> zolanaMobileSdkVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kZolanaMobileSdkVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kZolanaMobileSdkVersionConstMeta =>
      const TaskConstMeta(debugName: "sdk_version", argNames: []);

  @override
  Future<String> zolanaMobileShieldedAddress({required List<int> seed}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(seed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kZolanaMobileShieldedAddressConstMeta,
        argValues: [seed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kZolanaMobileShieldedAddressConstMeta =>
      const TaskConstMeta(debugName: "shielded_address", argNames: ["seed"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  TransferDraftRequest dco_decode_box_autoadd_transfer_draft_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_transfer_draft_request(raw);
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TransferDraftOutput> dco_decode_list_transfer_draft_output(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_transfer_draft_output)
        .toList();
  }

  @protected
  LocalProofResult dco_decode_local_proof_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return LocalProofResult(
      proofJson: dco_decode_String(arr[0]),
      verified: dco_decode_bool(arr[1]),
      inputs: dco_decode_u_32(arr[2]),
      outputs: dco_decode_u_32(arr[3]),
      keyLoadMs: dco_decode_u_64(arr[4]),
      proofMs: dco_decode_u_64(arr[5]),
      totalMs: dco_decode_u_64(arr[6]),
    );
  }

  @protected
  ProvingKeyInfo dco_decode_proving_key_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ProvingKeyInfo(
      inputs: dco_decode_u_32(arr[0]),
      outputs: dco_decode_u_32(arr[1]),
      requiresP256: dco_decode_bool(arr[2]),
      wires: dco_decode_u_64(arr[3]),
      publicWires: dco_decode_u_64(arr[4]),
      domainSize: dco_decode_u_64(arr[5]),
      constraintSystemOffset: dco_decode_u_64(arr[6]),
    );
  }

  @protected
  TransferDraft dco_decode_transfer_draft(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return TransferDraft(
      sender: dco_decode_String(arr[0]),
      recipient: dco_decode_String(arr[1]),
      inputLamports: dco_decode_u_64(arr[2]),
      transferLamports: dco_decode_u_64(arr[3]),
      changeLamports: dco_decode_u_64(arr[4]),
      shape: dco_decode_String(arr[5]),
      firstNullifierHex: dco_decode_String(arr[6]),
      externalDataHashHex: dco_decode_String(arr[7]),
      outputs: dco_decode_list_transfer_draft_output(arr[8]),
    );
  }

  @protected
  TransferDraftOutput dco_decode_transfer_draft_output(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TransferDraftOutput(
      owner: dco_decode_String(arr[0]),
      lamports: dco_decode_u_64(arr[1]),
      isChange: dco_decode_bool(arr[2]),
      isDummy: dco_decode_bool(arr[3]),
      commitmentHex: dco_decode_String(arr[4]),
    );
  }

  @protected
  TransferDraftRequest dco_decode_transfer_draft_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TransferDraftRequest(
      senderSeed: dco_decode_list_prim_u_8_strict(arr[0]),
      recipient: dco_decode_String(arr[1]),
      inputLamports: dco_decode_u_64(arr[2]),
      transferLamports: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  TransferDraftRequest sse_decode_box_autoadd_transfer_draft_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_transfer_draft_request(deserializer));
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TransferDraftOutput> sse_decode_list_transfer_draft_output(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TransferDraftOutput>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_transfer_draft_output(deserializer));
    }
    return ans_;
  }

  @protected
  LocalProofResult sse_decode_local_proof_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_proofJson = sse_decode_String(deserializer);
    var var_verified = sse_decode_bool(deserializer);
    var var_inputs = sse_decode_u_32(deserializer);
    var var_outputs = sse_decode_u_32(deserializer);
    var var_keyLoadMs = sse_decode_u_64(deserializer);
    var var_proofMs = sse_decode_u_64(deserializer);
    var var_totalMs = sse_decode_u_64(deserializer);
    return LocalProofResult(
      proofJson: var_proofJson,
      verified: var_verified,
      inputs: var_inputs,
      outputs: var_outputs,
      keyLoadMs: var_keyLoadMs,
      proofMs: var_proofMs,
      totalMs: var_totalMs,
    );
  }

  @protected
  ProvingKeyInfo sse_decode_proving_key_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_inputs = sse_decode_u_32(deserializer);
    var var_outputs = sse_decode_u_32(deserializer);
    var var_requiresP256 = sse_decode_bool(deserializer);
    var var_wires = sse_decode_u_64(deserializer);
    var var_publicWires = sse_decode_u_64(deserializer);
    var var_domainSize = sse_decode_u_64(deserializer);
    var var_constraintSystemOffset = sse_decode_u_64(deserializer);
    return ProvingKeyInfo(
      inputs: var_inputs,
      outputs: var_outputs,
      requiresP256: var_requiresP256,
      wires: var_wires,
      publicWires: var_publicWires,
      domainSize: var_domainSize,
      constraintSystemOffset: var_constraintSystemOffset,
    );
  }

  @protected
  TransferDraft sse_decode_transfer_draft(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sender = sse_decode_String(deserializer);
    var var_recipient = sse_decode_String(deserializer);
    var var_inputLamports = sse_decode_u_64(deserializer);
    var var_transferLamports = sse_decode_u_64(deserializer);
    var var_changeLamports = sse_decode_u_64(deserializer);
    var var_shape = sse_decode_String(deserializer);
    var var_firstNullifierHex = sse_decode_String(deserializer);
    var var_externalDataHashHex = sse_decode_String(deserializer);
    var var_outputs = sse_decode_list_transfer_draft_output(deserializer);
    return TransferDraft(
      sender: var_sender,
      recipient: var_recipient,
      inputLamports: var_inputLamports,
      transferLamports: var_transferLamports,
      changeLamports: var_changeLamports,
      shape: var_shape,
      firstNullifierHex: var_firstNullifierHex,
      externalDataHashHex: var_externalDataHashHex,
      outputs: var_outputs,
    );
  }

  @protected
  TransferDraftOutput sse_decode_transfer_draft_output(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_owner = sse_decode_String(deserializer);
    var var_lamports = sse_decode_u_64(deserializer);
    var var_isChange = sse_decode_bool(deserializer);
    var var_isDummy = sse_decode_bool(deserializer);
    var var_commitmentHex = sse_decode_String(deserializer);
    return TransferDraftOutput(
      owner: var_owner,
      lamports: var_lamports,
      isChange: var_isChange,
      isDummy: var_isDummy,
      commitmentHex: var_commitmentHex,
    );
  }

  @protected
  TransferDraftRequest sse_decode_transfer_draft_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_senderSeed = sse_decode_list_prim_u_8_strict(deserializer);
    var var_recipient = sse_decode_String(deserializer);
    var var_inputLamports = sse_decode_u_64(deserializer);
    var var_transferLamports = sse_decode_u_64(deserializer);
    return TransferDraftRequest(
      senderSeed: var_senderSeed,
      recipient: var_recipient,
      inputLamports: var_inputLamports,
      transferLamports: var_transferLamports,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_transfer_draft_request(
    TransferDraftRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_transfer_draft_request(self, serializer);
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_transfer_draft_output(
    List<TransferDraftOutput> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_transfer_draft_output(item, serializer);
    }
  }

  @protected
  void sse_encode_local_proof_result(
    LocalProofResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.proofJson, serializer);
    sse_encode_bool(self.verified, serializer);
    sse_encode_u_32(self.inputs, serializer);
    sse_encode_u_32(self.outputs, serializer);
    sse_encode_u_64(self.keyLoadMs, serializer);
    sse_encode_u_64(self.proofMs, serializer);
    sse_encode_u_64(self.totalMs, serializer);
  }

  @protected
  void sse_encode_proving_key_info(
    ProvingKeyInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.inputs, serializer);
    sse_encode_u_32(self.outputs, serializer);
    sse_encode_bool(self.requiresP256, serializer);
    sse_encode_u_64(self.wires, serializer);
    sse_encode_u_64(self.publicWires, serializer);
    sse_encode_u_64(self.domainSize, serializer);
    sse_encode_u_64(self.constraintSystemOffset, serializer);
  }

  @protected
  void sse_encode_transfer_draft(TransferDraft self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sender, serializer);
    sse_encode_String(self.recipient, serializer);
    sse_encode_u_64(self.inputLamports, serializer);
    sse_encode_u_64(self.transferLamports, serializer);
    sse_encode_u_64(self.changeLamports, serializer);
    sse_encode_String(self.shape, serializer);
    sse_encode_String(self.firstNullifierHex, serializer);
    sse_encode_String(self.externalDataHashHex, serializer);
    sse_encode_list_transfer_draft_output(self.outputs, serializer);
  }

  @protected
  void sse_encode_transfer_draft_output(
    TransferDraftOutput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.owner, serializer);
    sse_encode_u_64(self.lamports, serializer);
    sse_encode_bool(self.isChange, serializer);
    sse_encode_bool(self.isDummy, serializer);
    sse_encode_String(self.commitmentHex, serializer);
  }

  @protected
  void sse_encode_transfer_draft_request(
    TransferDraftRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.senderSeed, serializer);
    sse_encode_String(self.recipient, serializer);
    sse_encode_u_64(self.inputLamports, serializer);
    sse_encode_u_64(self.transferLamports, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
