// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1586915465;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__zolana_mobile__inspect_proving_key_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "inspect_proving_key",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = zolana_mobile::inspect_proving_key(api_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__zolana_mobile__poseidon_hash_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "poseidon_hash",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_inputs = <Vec<Vec<u8>>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = zolana_mobile::poseidon_hash(api_inputs)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__zolana_mobile__prepare_transfer_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "prepare_transfer",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request = <zolana_mobile::TransferDraftRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = zolana_mobile::prepare_transfer(api_request)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__zolana_mobile__prove_assignment_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "prove_assignment",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_proving_key_path = <String>::sse_decode(&mut deserializer);
            let api_assignment_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok =
                        zolana_mobile::prove_assignment(api_proving_key_path, api_assignment_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__zolana_mobile__sdk_version_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "sdk_version",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(zolana_mobile::sdk_version())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__zolana_mobile__shielded_address_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "shielded_address",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_seed = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = zolana_mobile::shielded_address(api_seed)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: static_checks

#[allow(clippy::unnecessary_literal_unwrap)]
const _: fn() = || {
    {
        let LocalProofResult = None::<zolana_mobile::LocalProofResult>.unwrap();
        let _: String = LocalProofResult.proof_json;
        let _: bool = LocalProofResult.verified;
        let _: u32 = LocalProofResult.inputs;
        let _: u32 = LocalProofResult.outputs;
        let _: u64 = LocalProofResult.key_load_ms;
        let _: u64 = LocalProofResult.proof_ms;
        let _: u64 = LocalProofResult.total_ms;
    }
    {
        let ProvingKeyInfo = None::<zolana_mobile::ProvingKeyInfo>.unwrap();
        let _: u32 = ProvingKeyInfo.inputs;
        let _: u32 = ProvingKeyInfo.outputs;
        let _: bool = ProvingKeyInfo.requires_p256;
        let _: u64 = ProvingKeyInfo.wires;
        let _: u64 = ProvingKeyInfo.public_wires;
        let _: u64 = ProvingKeyInfo.domain_size;
        let _: u64 = ProvingKeyInfo.constraint_system_offset;
    }
    {
        let TransferDraft = None::<zolana_mobile::TransferDraft>.unwrap();
        let _: String = TransferDraft.sender;
        let _: String = TransferDraft.recipient;
        let _: u64 = TransferDraft.input_lamports;
        let _: u64 = TransferDraft.transfer_lamports;
        let _: u64 = TransferDraft.change_lamports;
        let _: String = TransferDraft.shape;
        let _: String = TransferDraft.first_nullifier_hex;
        let _: String = TransferDraft.external_data_hash_hex;
        let _: Vec<zolana_mobile::TransferDraftOutput> = TransferDraft.outputs;
    }
    {
        let TransferDraftOutput = None::<zolana_mobile::TransferDraftOutput>.unwrap();
        let _: String = TransferDraftOutput.owner;
        let _: u64 = TransferDraftOutput.lamports;
        let _: bool = TransferDraftOutput.is_change;
        let _: bool = TransferDraftOutput.is_dummy;
        let _: String = TransferDraftOutput.commitment_hex;
    }
    {
        let TransferDraftRequest = None::<zolana_mobile::TransferDraftRequest>.unwrap();
        let _: Vec<u8> = TransferDraftRequest.sender_seed;
        let _: String = TransferDraftRequest.recipient;
        let _: u64 = TransferDraftRequest.input_lamports;
        let _: u64 = TransferDraftRequest.transfer_lamports;
    }
};

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for Vec<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<Vec<u8>>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<zolana_mobile::TransferDraftOutput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<zolana_mobile::TransferDraftOutput>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for zolana_mobile::LocalProofResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_proofJson = <String>::sse_decode(deserializer);
        let mut var_verified = <bool>::sse_decode(deserializer);
        let mut var_inputs = <u32>::sse_decode(deserializer);
        let mut var_outputs = <u32>::sse_decode(deserializer);
        let mut var_keyLoadMs = <u64>::sse_decode(deserializer);
        let mut var_proofMs = <u64>::sse_decode(deserializer);
        let mut var_totalMs = <u64>::sse_decode(deserializer);
        return zolana_mobile::LocalProofResult {
            proof_json: var_proofJson,
            verified: var_verified,
            inputs: var_inputs,
            outputs: var_outputs,
            key_load_ms: var_keyLoadMs,
            proof_ms: var_proofMs,
            total_ms: var_totalMs,
        };
    }
}

impl SseDecode for zolana_mobile::ProvingKeyInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputs = <u32>::sse_decode(deserializer);
        let mut var_outputs = <u32>::sse_decode(deserializer);
        let mut var_requiresP256 = <bool>::sse_decode(deserializer);
        let mut var_wires = <u64>::sse_decode(deserializer);
        let mut var_publicWires = <u64>::sse_decode(deserializer);
        let mut var_domainSize = <u64>::sse_decode(deserializer);
        let mut var_constraintSystemOffset = <u64>::sse_decode(deserializer);
        return zolana_mobile::ProvingKeyInfo {
            inputs: var_inputs,
            outputs: var_outputs,
            requires_p256: var_requiresP256,
            wires: var_wires,
            public_wires: var_publicWires,
            domain_size: var_domainSize,
            constraint_system_offset: var_constraintSystemOffset,
        };
    }
}

impl SseDecode for zolana_mobile::TransferDraft {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sender = <String>::sse_decode(deserializer);
        let mut var_recipient = <String>::sse_decode(deserializer);
        let mut var_inputLamports = <u64>::sse_decode(deserializer);
        let mut var_transferLamports = <u64>::sse_decode(deserializer);
        let mut var_changeLamports = <u64>::sse_decode(deserializer);
        let mut var_shape = <String>::sse_decode(deserializer);
        let mut var_firstNullifierHex = <String>::sse_decode(deserializer);
        let mut var_externalDataHashHex = <String>::sse_decode(deserializer);
        let mut var_outputs = <Vec<zolana_mobile::TransferDraftOutput>>::sse_decode(deserializer);
        return zolana_mobile::TransferDraft {
            sender: var_sender,
            recipient: var_recipient,
            input_lamports: var_inputLamports,
            transfer_lamports: var_transferLamports,
            change_lamports: var_changeLamports,
            shape: var_shape,
            first_nullifier_hex: var_firstNullifierHex,
            external_data_hash_hex: var_externalDataHashHex,
            outputs: var_outputs,
        };
    }
}

impl SseDecode for zolana_mobile::TransferDraftOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_owner = <String>::sse_decode(deserializer);
        let mut var_lamports = <u64>::sse_decode(deserializer);
        let mut var_isChange = <bool>::sse_decode(deserializer);
        let mut var_isDummy = <bool>::sse_decode(deserializer);
        let mut var_commitmentHex = <String>::sse_decode(deserializer);
        return zolana_mobile::TransferDraftOutput {
            owner: var_owner,
            lamports: var_lamports,
            is_change: var_isChange,
            is_dummy: var_isDummy,
            commitment_hex: var_commitmentHex,
        };
    }
}

impl SseDecode for zolana_mobile::TransferDraftRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_senderSeed = <Vec<u8>>::sse_decode(deserializer);
        let mut var_recipient = <String>::sse_decode(deserializer);
        let mut var_inputLamports = <u64>::sse_decode(deserializer);
        let mut var_transferLamports = <u64>::sse_decode(deserializer);
        return zolana_mobile::TransferDraftRequest {
            sender_seed: var_senderSeed,
            recipient: var_recipient,
            input_lamports: var_inputLamports,
            transfer_lamports: var_transferLamports,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__zolana_mobile__inspect_proving_key_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__zolana_mobile__poseidon_hash_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__zolana_mobile__prepare_transfer_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__zolana_mobile__prove_assignment_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__zolana_mobile__sdk_version_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__zolana_mobile__shielded_address_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<zolana_mobile::LocalProofResult> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.proof_json.into_into_dart().into_dart(),
            self.0.verified.into_into_dart().into_dart(),
            self.0.inputs.into_into_dart().into_dart(),
            self.0.outputs.into_into_dart().into_dart(),
            self.0.key_load_ms.into_into_dart().into_dart(),
            self.0.proof_ms.into_into_dart().into_dart(),
            self.0.total_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<zolana_mobile::LocalProofResult>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<zolana_mobile::LocalProofResult>>
    for zolana_mobile::LocalProofResult
{
    fn into_into_dart(self) -> FrbWrapper<zolana_mobile::LocalProofResult> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<zolana_mobile::ProvingKeyInfo> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.inputs.into_into_dart().into_dart(),
            self.0.outputs.into_into_dart().into_dart(),
            self.0.requires_p256.into_into_dart().into_dart(),
            self.0.wires.into_into_dart().into_dart(),
            self.0.public_wires.into_into_dart().into_dart(),
            self.0.domain_size.into_into_dart().into_dart(),
            self.0.constraint_system_offset.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<zolana_mobile::ProvingKeyInfo>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<zolana_mobile::ProvingKeyInfo>>
    for zolana_mobile::ProvingKeyInfo
{
    fn into_into_dart(self) -> FrbWrapper<zolana_mobile::ProvingKeyInfo> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<zolana_mobile::TransferDraft> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.sender.into_into_dart().into_dart(),
            self.0.recipient.into_into_dart().into_dart(),
            self.0.input_lamports.into_into_dart().into_dart(),
            self.0.transfer_lamports.into_into_dart().into_dart(),
            self.0.change_lamports.into_into_dart().into_dart(),
            self.0.shape.into_into_dart().into_dart(),
            self.0.first_nullifier_hex.into_into_dart().into_dart(),
            self.0.external_data_hash_hex.into_into_dart().into_dart(),
            self.0.outputs.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<zolana_mobile::TransferDraft>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<zolana_mobile::TransferDraft>>
    for zolana_mobile::TransferDraft
{
    fn into_into_dart(self) -> FrbWrapper<zolana_mobile::TransferDraft> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<zolana_mobile::TransferDraftOutput> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.owner.into_into_dart().into_dart(),
            self.0.lamports.into_into_dart().into_dart(),
            self.0.is_change.into_into_dart().into_dart(),
            self.0.is_dummy.into_into_dart().into_dart(),
            self.0.commitment_hex.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<zolana_mobile::TransferDraftOutput>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<zolana_mobile::TransferDraftOutput>>
    for zolana_mobile::TransferDraftOutput
{
    fn into_into_dart(self) -> FrbWrapper<zolana_mobile::TransferDraftOutput> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<zolana_mobile::TransferDraftRequest> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.sender_seed.into_into_dart().into_dart(),
            self.0.recipient.into_into_dart().into_dart(),
            self.0.input_lamports.into_into_dart().into_dart(),
            self.0.transfer_lamports.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<zolana_mobile::TransferDraftRequest>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<zolana_mobile::TransferDraftRequest>>
    for zolana_mobile::TransferDraftRequest
{
    fn into_into_dart(self) -> FrbWrapper<zolana_mobile::TransferDraftRequest> {
        self.into()
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for Vec<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <Vec<u8>>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<zolana_mobile::TransferDraftOutput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <zolana_mobile::TransferDraftOutput>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for zolana_mobile::LocalProofResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.proof_json, serializer);
        <bool>::sse_encode(self.verified, serializer);
        <u32>::sse_encode(self.inputs, serializer);
        <u32>::sse_encode(self.outputs, serializer);
        <u64>::sse_encode(self.key_load_ms, serializer);
        <u64>::sse_encode(self.proof_ms, serializer);
        <u64>::sse_encode(self.total_ms, serializer);
    }
}

impl SseEncode for zolana_mobile::ProvingKeyInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.inputs, serializer);
        <u32>::sse_encode(self.outputs, serializer);
        <bool>::sse_encode(self.requires_p256, serializer);
        <u64>::sse_encode(self.wires, serializer);
        <u64>::sse_encode(self.public_wires, serializer);
        <u64>::sse_encode(self.domain_size, serializer);
        <u64>::sse_encode(self.constraint_system_offset, serializer);
    }
}

impl SseEncode for zolana_mobile::TransferDraft {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.sender, serializer);
        <String>::sse_encode(self.recipient, serializer);
        <u64>::sse_encode(self.input_lamports, serializer);
        <u64>::sse_encode(self.transfer_lamports, serializer);
        <u64>::sse_encode(self.change_lamports, serializer);
        <String>::sse_encode(self.shape, serializer);
        <String>::sse_encode(self.first_nullifier_hex, serializer);
        <String>::sse_encode(self.external_data_hash_hex, serializer);
        <Vec<zolana_mobile::TransferDraftOutput>>::sse_encode(self.outputs, serializer);
    }
}

impl SseEncode for zolana_mobile::TransferDraftOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.owner, serializer);
        <u64>::sse_encode(self.lamports, serializer);
        <bool>::sse_encode(self.is_change, serializer);
        <bool>::sse_encode(self.is_dummy, serializer);
        <String>::sse_encode(self.commitment_hex, serializer);
    }
}

impl SseEncode for zolana_mobile::TransferDraftRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.sender_seed, serializer);
        <String>::sse_encode(self.recipient, serializer);
        <u64>::sse_encode(self.input_lamports, serializer);
        <u64>::sse_encode(self.transfer_lamports, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
